// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/homespendapi/service/budgets/proto/budget.proto

/*
Package budget is a generated protocol buffer package.

It is generated from these files:
	github.com/homespendapi/service/budgets/proto/budget.proto

It has these top-level messages:
	CreateBudgetRequest
	CreateBudgetResponse
	Budget
*/
package budget

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import utils "github.com/homespendapi/service/utils/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BudgetStat int32

const (
	BudgetStat_error     BudgetStat = 0
	BudgetStat_avaliable BudgetStat = 1
	BudgetStat_broke     BudgetStat = 2
)

var BudgetStat_name = map[int32]string{
	0: "error",
	1: "avaliable",
	2: "broke",
}
var BudgetStat_value = map[string]int32{
	"error":     0,
	"avaliable": 1,
	"broke":     2,
}

func (x BudgetStat) String() string {
	return proto.EnumName(BudgetStat_name, int32(x))
}
func (BudgetStat) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateBudgetRequest struct {
	Budget *Budget `protobuf:"bytes,1,opt,name=budget" json:"budget,omitempty"`
}

func (m *CreateBudgetRequest) Reset()                    { *m = CreateBudgetRequest{} }
func (m *CreateBudgetRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBudgetRequest) ProtoMessage()               {}
func (*CreateBudgetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateBudgetRequest) GetBudget() *Budget {
	if m != nil {
		return m.Budget
	}
	return nil
}

type CreateBudgetResponse struct {
	RespMsg *utils.RespMsg `protobuf:"bytes,1,opt,name=resp_msg,json=respMsg" json:"resp_msg,omitempty"`
}

func (m *CreateBudgetResponse) Reset()                    { *m = CreateBudgetResponse{} }
func (m *CreateBudgetResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateBudgetResponse) ProtoMessage()               {}
func (*CreateBudgetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateBudgetResponse) GetRespMsg() *utils.RespMsg {
	if m != nil {
		return m.RespMsg
	}
	return nil
}

type Budget struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BudgetName  string                     `protobuf:"bytes,2,opt,name=budget_name,json=budgetName" json:"budget_name,omitempty"`
	BudgetIcon  string                     `protobuf:"bytes,3,opt,name=budget_icon,json=budgetIcon" json:"budget_icon,omitempty"`
	AuthoriseBy string                     `protobuf:"bytes,4,opt,name=authorise_by,json=authoriseBy" json:"authorise_by,omitempty"`
	Stat        BudgetStat                 `protobuf:"varint,5,opt,name=stat,enum=budget.BudgetStat" json:"stat,omitempty"`
	Decs        string                     `protobuf:"bytes,6,opt,name=decs" json:"decs,omitempty"`
	CreateAt    *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=create_at,json=createAt" json:"create_at,omitempty"`
	UpdateAt    *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=update_at,json=updateAt" json:"update_at,omitempty"`
}

func (m *Budget) Reset()                    { *m = Budget{} }
func (m *Budget) String() string            { return proto.CompactTextString(m) }
func (*Budget) ProtoMessage()               {}
func (*Budget) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Budget) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Budget) GetBudgetName() string {
	if m != nil {
		return m.BudgetName
	}
	return ""
}

func (m *Budget) GetBudgetIcon() string {
	if m != nil {
		return m.BudgetIcon
	}
	return ""
}

func (m *Budget) GetAuthoriseBy() string {
	if m != nil {
		return m.AuthoriseBy
	}
	return ""
}

func (m *Budget) GetStat() BudgetStat {
	if m != nil {
		return m.Stat
	}
	return BudgetStat_error
}

func (m *Budget) GetDecs() string {
	if m != nil {
		return m.Decs
	}
	return ""
}

func (m *Budget) GetCreateAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

func (m *Budget) GetUpdateAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdateAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateBudgetRequest)(nil), "budget.CreateBudgetRequest")
	proto.RegisterType((*CreateBudgetResponse)(nil), "budget.CreateBudgetResponse")
	proto.RegisterType((*Budget)(nil), "budget.Budget")
	proto.RegisterEnum("budget.BudgetStat", BudgetStat_name, BudgetStat_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Budgets service

type BudgetsClient interface {
	// Create a Budget
	CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*CreateBudgetResponse, error)
}

type budgetsClient struct {
	cc *grpc.ClientConn
}

func NewBudgetsClient(cc *grpc.ClientConn) BudgetsClient {
	return &budgetsClient{cc}
}

func (c *budgetsClient) CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*CreateBudgetResponse, error) {
	out := new(CreateBudgetResponse)
	err := grpc.Invoke(ctx, "/budget.Budgets/CreateBudget", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Budgets service

type BudgetsServer interface {
	// Create a Budget
	CreateBudget(context.Context, *CreateBudgetRequest) (*CreateBudgetResponse, error)
}

func RegisterBudgetsServer(s *grpc.Server, srv BudgetsServer) {
	s.RegisterService(&_Budgets_serviceDesc, srv)
}

func _Budgets_CreateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetsServer).CreateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/budget.Budgets/CreateBudget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetsServer).CreateBudget(ctx, req.(*CreateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Budgets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "budget.Budgets",
	HandlerType: (*BudgetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBudget",
			Handler:    _Budgets_CreateBudget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/homespendapi/service/budgets/proto/budget.proto",
}

func init() {
	proto.RegisterFile("github.com/homespendapi/service/budgets/proto/budget.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0x6b, 0x37, 0x75, 0xe2, 0x49, 0x89, 0xa2, 0x85, 0x83, 0x65, 0x90, 0x1a, 0x7c, 0xa8,
	0x02, 0x07, 0x5b, 0x84, 0x43, 0x25, 0x24, 0x0e, 0x29, 0x27, 0x84, 0xe0, 0x60, 0x10, 0x57, 0x6b,
	0x6d, 0x0f, 0xce, 0x0a, 0xdb, 0x6b, 0x76, 0xc7, 0x95, 0xfa, 0x9b, 0xf8, 0x93, 0x28, 0xbb, 0x76,
	0x49, 0xa4, 0x48, 0xb9, 0xcd, 0x78, 0xbe, 0xb7, 0x6f, 0x46, 0xcf, 0xf0, 0xa1, 0x12, 0xb4, 0xeb,
	0xf3, 0xb8, 0x90, 0x4d, 0xb2, 0x93, 0x0d, 0xea, 0x0e, 0xdb, 0x92, 0x77, 0x22, 0xd1, 0xa8, 0x1e,
	0x44, 0x81, 0x49, 0xde, 0x97, 0x15, 0x92, 0x4e, 0x3a, 0x25, 0x49, 0x0e, 0x5d, 0x6c, 0x1a, 0xe6,
	0xd9, 0x2e, 0xbc, 0xa9, 0xa4, 0xac, 0x6a, 0xb4, 0x48, 0xde, 0xff, 0x4a, 0x48, 0x34, 0xa8, 0x89,
	0x37, 0x9d, 0x05, 0xc3, 0xbb, 0x73, 0x26, 0x3d, 0x89, 0x7a, 0xb4, 0x30, 0xb5, 0x15, 0x46, 0x1f,
	0xe1, 0xf9, 0x27, 0x85, 0x9c, 0xf0, 0xde, 0x38, 0xa5, 0xf8, 0xa7, 0x47, 0x4d, 0xec, 0x16, 0x06,
	0xeb, 0xc0, 0x59, 0x39, 0xeb, 0xf9, 0x66, 0x11, 0x0f, 0x7b, 0x0d, 0xd8, 0x30, 0x8d, 0xb6, 0xf0,
	0xe2, 0x58, 0xae, 0x3b, 0xd9, 0x6a, 0x64, 0x6f, 0x60, 0xa6, 0x50, 0x77, 0x59, 0xa3, 0xab, 0xa7,
	0x17, 0xac, 0xed, 0x1e, 0xf9, 0xaa, 0xab, 0x74, 0xaa, 0x6c, 0x11, 0xfd, 0x75, 0xc1, 0xb3, 0x6a,
	0xb6, 0x00, 0x57, 0x94, 0x86, 0xbf, 0x4c, 0x5d, 0x51, 0xb2, 0x1b, 0x98, 0x5b, 0x9f, 0xac, 0xe5,
	0x0d, 0x06, 0xee, 0xca, 0x59, 0xfb, 0x29, 0xd8, 0x4f, 0xdf, 0x78, 0x83, 0x07, 0x80, 0x28, 0x64,
	0x1b, 0x5c, 0x1e, 0x02, 0x9f, 0x0b, 0xd9, 0xb2, 0xd7, 0x70, 0xcd, 0x7b, 0xda, 0x49, 0x25, 0x34,
	0x66, 0xf9, 0x63, 0x30, 0x31, 0xc4, 0xfc, 0xe9, 0xdb, 0xfd, 0x23, 0xbb, 0x85, 0x89, 0x26, 0x4e,
	0xc1, 0xd5, 0xca, 0x59, 0x2f, 0x36, 0xec, 0xf8, 0xd0, 0xef, 0xc4, 0x29, 0x35, 0x73, 0xc6, 0x60,
	0x52, 0x62, 0xa1, 0x03, 0xcf, 0x3c, 0x61, 0x6a, 0x76, 0x07, 0x7e, 0x61, 0xce, 0xcf, 0x38, 0x05,
	0x53, 0x73, 0x67, 0x18, 0xdb, 0xac, 0xe2, 0x31, 0xab, 0xf8, 0xc7, 0x98, 0x55, 0x3a, 0xb3, 0xf0,
	0x96, 0xf6, 0xc2, 0xbe, 0x2b, 0x07, 0xe1, 0xec, 0xbc, 0xd0, 0xc2, 0x5b, 0x7a, 0xfb, 0x0e, 0xe0,
	0xff, 0x66, 0xcc, 0x87, 0x2b, 0x54, 0x4a, 0xaa, 0xe5, 0x05, 0x7b, 0x06, 0x3e, 0x7f, 0xe0, 0xb5,
	0xe0, 0x79, 0x8d, 0x4b, 0x67, 0x3f, 0xc9, 0x95, 0xfc, 0x8d, 0x4b, 0x77, 0xf3, 0x13, 0xa6, 0x56,
	0xa2, 0xd9, 0x17, 0xb8, 0x3e, 0x8c, 0x8b, 0xbd, 0x1c, 0xaf, 0x3d, 0xf1, 0x0f, 0x84, 0xaf, 0x4e,
	0x0f, 0x6d, 0xc2, 0xd1, 0x45, 0xee, 0x99, 0x45, 0xdf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd4,
	0xcf, 0xe8, 0x09, 0xe1, 0x02, 0x00, 0x00,
}
