// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/homespendapi/service/accounts/proto/account.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	github.com/homespendapi/service/accounts/proto/account.proto

It has these top-level messages:
	CreateAccountRequest
	CreateAccountResponse
	Account
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import utils "github.com/homespendapi/service/utils/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountStat int32

const (
	AccountStat_error      AccountStat = 0
	AccountStat_pending    AccountStat = 1
	AccountStat_transfered AccountStat = 2
	AccountStat_removed    AccountStat = 99
)

var AccountStat_name = map[int32]string{
	0:  "error",
	1:  "pending",
	2:  "transfered",
	99: "removed",
}
var AccountStat_value = map[string]int32{
	"error":      0,
	"pending":    1,
	"transfered": 2,
	"removed":    99,
}

func (x AccountStat) String() string {
	return proto.EnumName(AccountStat_name, int32(x))
}
func (AccountStat) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateAccountRequest struct {
	Account  *Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	BudgetID int64    `protobuf:"varint,2,opt,name=BudgetID" json:"BudgetID,omitempty"`
}

func (m *CreateAccountRequest) Reset()                    { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()               {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateAccountRequest) GetBudgetID() int64 {
	if m != nil {
		return m.BudgetID
	}
	return 0
}

type CreateAccountResponse struct {
	RespMsg *utils.RespMsg `protobuf:"bytes,1,opt,name=resp_msg,json=respMsg" json:"resp_msg,omitempty"`
}

func (m *CreateAccountResponse) Reset()                    { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()               {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountResponse) GetRespMsg() *utils.RespMsg {
	if m != nil {
		return m.RespMsg
	}
	return nil
}

type Account struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ColumnName  string                     `protobuf:"bytes,2,opt,name=column_name,json=columnName" json:"column_name,omitempty"`
	Amount      float32                    `protobuf:"fixed32,3,opt,name=amount" json:"amount,omitempty"`
	Stat        AccountStat                `protobuf:"varint,4,opt,name=stat,enum=account.AccountStat" json:"stat,omitempty"`
	Remark      string                     `protobuf:"bytes,5,opt,name=remark" json:"remark,omitempty"`
	AuthoriseBy string                     `protobuf:"bytes,6,opt,name=authorise_by,json=authoriseBy" json:"authorise_by,omitempty"`
	PrepareBy   string                     `protobuf:"bytes,7,opt,name=prepare_by,json=prepareBy" json:"prepare_by,omitempty"`
	CreateAt    *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=create_at,json=createAt" json:"create_at,omitempty"`
	UpdateAt    *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=update_at,json=updateAt" json:"update_at,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetColumnName() string {
	if m != nil {
		return m.ColumnName
	}
	return ""
}

func (m *Account) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Account) GetStat() AccountStat {
	if m != nil {
		return m.Stat
	}
	return AccountStat_error
}

func (m *Account) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *Account) GetAuthoriseBy() string {
	if m != nil {
		return m.AuthoriseBy
	}
	return ""
}

func (m *Account) GetPrepareBy() string {
	if m != nil {
		return m.PrepareBy
	}
	return ""
}

func (m *Account) GetCreateAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

func (m *Account) GetUpdateAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdateAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "account.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "account.CreateAccountResponse")
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterEnum("account.AccountStat", AccountStat_name, AccountStat_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Accounts service

type AccountsClient interface {
	// Create a Account
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := grpc.Invoke(ctx, "/account.Accounts/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	// Create a Account
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Accounts_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/homespendapi/service/accounts/proto/account.proto",
}

func init() {
	proto.RegisterFile("github.com/homespendapi/service/accounts/proto/account.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x9d, 0x36, 0xb6, 0xc7, 0x10, 0x59, 0xab, 0x82, 0x2c, 0x4b, 0xa5, 0x21, 0x27, 0xd3,
	0x83, 0x2d, 0x85, 0x43, 0x2f, 0x5c, 0x62, 0xb8, 0x70, 0x00, 0x21, 0xc3, 0x11, 0x11, 0x6d, 0xec,
	0xa9, 0x63, 0x91, 0xf5, 0x9a, 0xfd, 0xa8, 0x94, 0x7f, 0xc8, 0xcf, 0x42, 0xde, 0xb5, 0x23, 0xa8,
	0xa8, 0x7a, 0xdb, 0xb7, 0xf3, 0xde, 0xbc, 0xf9, 0x82, 0x77, 0x4d, 0xab, 0xf6, 0x7a, 0x97, 0x55,
	0x9c, 0xe5, 0x7b, 0xce, 0x50, 0xf6, 0xd8, 0xd5, 0xb4, 0x6f, 0x73, 0x89, 0xe2, 0xbe, 0xad, 0x30,
	0xa7, 0x55, 0xc5, 0x75, 0xa7, 0x64, 0xde, 0x0b, 0xae, 0xf8, 0x04, 0x33, 0x83, 0x88, 0x37, 0xc2,
	0xe4, 0xba, 0xe1, 0xbc, 0x39, 0xa0, 0x25, 0xed, 0xf4, 0x5d, 0xae, 0x5a, 0x86, 0x52, 0x51, 0xd6,
	0x5b, 0x66, 0x72, 0xfb, 0x94, 0x8f, 0x56, 0xed, 0x61, 0x32, 0x31, 0x6f, 0x2b, 0x5c, 0xfd, 0x80,
	0xcb, 0xf7, 0x02, 0xa9, 0xc2, 0x8d, 0xb5, 0x2a, 0xf1, 0x97, 0x46, 0xa9, 0xc8, 0x0d, 0x4c, 0xe6,
	0xb1, 0xb3, 0x74, 0xd2, 0x70, 0x1d, 0x65, 0x53, 0x6d, 0x13, 0x73, 0x22, 0x90, 0x04, 0xfc, 0x42,
	0xd7, 0x0d, 0xaa, 0x8f, 0x1f, 0x62, 0x77, 0xe9, 0xa4, 0xb3, 0xf2, 0x84, 0x57, 0x05, 0xbc, 0x78,
	0x90, 0x5f, 0xf6, 0xbc, 0x93, 0x48, 0xde, 0x80, 0x2f, 0x50, 0xf6, 0x5b, 0x26, 0x9b, 0xd1, 0x61,
	0x91, 0xd9, 0xc2, 0x06, 0xca, 0x27, 0xd9, 0x94, 0x9e, 0xb0, 0x8f, 0xd5, 0x6f, 0x17, 0xbc, 0x51,
	0x4e, 0x16, 0xe0, 0xb6, 0xb5, 0x11, 0xcc, 0x4a, 0xb7, 0xad, 0xc9, 0x35, 0x84, 0x15, 0x3f, 0x68,
	0xd6, 0x6d, 0x3b, 0xca, 0xd0, 0xd8, 0x07, 0x25, 0xd8, 0xaf, 0xcf, 0x94, 0x21, 0x79, 0x09, 0x73,
	0xca, 0x4c, 0x1f, 0xb3, 0xa5, 0x93, 0xba, 0xe5, 0x88, 0x48, 0x0a, 0xe7, 0x52, 0x51, 0x15, 0x9f,
	0x2f, 0x9d, 0x74, 0xb1, 0xbe, 0x7c, 0xd8, 0xdd, 0x57, 0x45, 0x55, 0x69, 0x18, 0x43, 0x06, 0x81,
	0x8c, 0x8a, 0x9f, 0xf1, 0x85, 0xc9, 0x3e, 0x22, 0xf2, 0x1a, 0x9e, 0x51, 0xad, 0xf6, 0x5c, 0xb4,
	0x12, 0xb7, 0xbb, 0x63, 0x3c, 0x37, 0xd1, 0xf0, 0xf4, 0x57, 0x1c, 0xc9, 0x15, 0x40, 0x2f, 0xb0,
	0xa7, 0xc2, 0x10, 0x3c, 0x43, 0x08, 0xc6, 0x9f, 0xe2, 0x48, 0x6e, 0x21, 0xa8, 0xcc, 0x70, 0xb6,
	0x54, 0xc5, 0xbe, 0x19, 0x42, 0x92, 0xd9, 0x55, 0x67, 0xd3, 0xaa, 0xb3, 0x6f, 0xd3, 0xaa, 0x4b,
	0xdf, 0x92, 0x37, 0x6a, 0x10, 0xea, 0xbe, 0x1e, 0x85, 0xc1, 0xd3, 0x42, 0x4b, 0xde, 0xa8, 0x9b,
	0x02, 0xc2, 0xbf, 0x1a, 0x24, 0x01, 0x5c, 0xa0, 0x10, 0x5c, 0x44, 0x67, 0x24, 0x04, 0x6f, 0xb8,
	0x99, 0xb6, 0x6b, 0x22, 0x87, 0x2c, 0x00, 0x94, 0xa0, 0x9d, 0xbc, 0x43, 0x81, 0x75, 0xe4, 0x0e,
	0x41, 0x81, 0x8c, 0xdf, 0x63, 0x1d, 0x55, 0xeb, 0xef, 0xe0, 0x8f, 0x39, 0x24, 0xf9, 0x02, 0xcf,
	0xff, 0x59, 0x2f, 0xb9, 0x3a, 0x0d, 0xf2, 0x7f, 0x67, 0x95, 0xbc, 0x7a, 0x2c, 0x6c, 0xaf, 0x62,
	0x75, 0xb6, 0x9b, 0x9b, 0xfa, 0xdf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x82, 0x77, 0xaf, 0xec,
	0x3a, 0x03, 0x00, 0x00,
}
